---
services:
  loki:
    container_name: loki
    image: grafana/loki:${LOKI_TAG:-3.4.3}
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml

  grafana-agent:
    container_name: grafana-agent
    image: grafana/agent:${GRAFANA_AGENT_TAG:-v0.44.2}
    environment:
      WAL_DATA_DIRECTORY: "/etc/agent/data"
      CONFIG_FILE_PATH:  "/etc/agent/agent.yaml"
    volumes:
      - ./data/:/etc/agent/data
      - ./config/agent.yaml/:/etc/agent/agent.yaml

  grafana:
    container_name: grafana
    image: grafana/grafana:${GRAFANA_TAG:-11.6.1}
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    ports:
      - 3000:3000
